"""
MarketMind AI – Report Generator
Formats the research output into structured HTML and JSON reports.
"""

import json
from datetime import datetime
from typing import Dict


class ReportGenerator:
    def generate(self, data: dict, fmt: str = "html") -> dict:
        if fmt == "html":
            return {"format": "html", "content": self._generate_html(data), "generated_at": datetime.now().isoformat()}
        return {"format": "json", "content": data, "generated_at": datetime.now().isoformat()}

    def _generate_html(self, data: dict) -> str:
        report = data.get("report", {})
        research = data.get("research", {})
        meta = data.get("meta", {})

        market = meta.get("market", research.get("market_name", "Market Research Report"))
        findings = report.get("key_findings", [])
        recommendations = report.get("strategic_recommendations", [])
        sources = report.get("sources_used", [])

        findings_html = "".join(f"<li>{f}</li>" for f in findings)
        rec_html = "".join(
            f'<li><span class="priority-{r.get("priority","").lower()}">[{r.get("priority","")}]</span> {r.get("recommendation","")}'
            f'<br><small>{r.get("rationale","")}</small></li>'
            for r in recommendations
        )
        sources_html = "".join(f"<li>{s}</li>" for s in sources)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>MarketMind AI Report – {market}</title>
<style>
  body {{ font-family: -apple-system,Segoe UI,sans-serif; margin: 40px auto; max-width: 860px; color: #1f2328; line-height: 1.7; }}
  h1 {{ color: #3b82d4; border-bottom: 2px solid #3b82d4; padding-bottom: 10px; }}
  h2 {{ color: #1f2328; margin-top: 32px; border-left: 4px solid #3b82d4; padding-left: 12px; }}
  .meta {{ color: #57606a; font-size: 13px; margin-bottom: 24px; }}
  .section {{ background: #f7f8fa; border-radius: 8px; padding: 20px 24px; margin: 16px 0; }}
  li {{ margin: 8px 0; }}
  .priority-high {{ color: #dc2626; font-weight: bold; }}
  .priority-medium {{ color: #d97706; font-weight: bold; }}
  .priority-low {{ color: #16a34a; font-weight: bold; }}
  .confidence {{ background: #dbeafe; border-radius: 4px; padding: 8px 14px; font-size: 13px; }}
  .footer {{ text-align: center; color: #57606a; font-size: 12px; border-top: 1px solid #e5e7eb; margin-top: 40px; padding-top: 16px; }}
</style>
</head>
<body>
<h1>📊 {market}</h1>
<p class="meta">Generated by <strong>MarketMind AI</strong> — Powered by IBM Granite via IBM watsonx.ai<br>
Report Date: {report.get("report_date", datetime.now().strftime("%Y-%m-%d"))}</p>

<h2>Executive Summary</h2>
<div class="section"><p>{report.get("executive_summary", "")}</p></div>

<h2>Key Findings</h2>
<div class="section"><ul>{findings_html}</ul></div>

<h2>Strategic Recommendations</h2>
<div class="section"><ul>{rec_html}</ul></div>

<h2>Conclusion</h2>
<div class="section"><p>{report.get("conclusion", "")}</p></div>

<h2>Sources & Attribution</h2>
<div class="section"><ul>{sources_html}</ul></div>

<div class="confidence">
  <strong>Confidence Rating:</strong> {report.get("confidence_rating", "N/A")}
</div>

<div class="footer">
  Generated by MarketMind AI · IBM Granite · IBM watsonx.ai<br>
  ⚠️ AI-generated analysis — validate before financial decisions.
</div>
</body>
</html>"""
